### ISSUE TITLE
Step 2 in the installation process is unclear.

### ISSUE THREAD

**Issue by Brandons404** [qbalsdon/pico_rgb_keypad_hid#10]
It looks like a ton of work was put into this project and I really want to get started and play around, but following the instructions, step 2 is a little confusing. 

> Copy all my python scripts, including code.py to the CIRCUITPY/ directory.

Which python scripts exactly? Should I be putting the entire repo onto my board? I guess I am unsure which folders/files to exclude, if any. I dragged over what I thought were the right ones, and windows said it would take 30 minutes so it feels wrong. I've tried a few different combinations and all have resulted in errors.

**Comment by qbalsdon** [comment]
I updated the readme to include mentioning the `lib` and `keyconfig` folders - they contain all the .py scripts.
