### ISSUE TITLE
Pico Display

### ISSUE THREAD

**Issue by kjbaker-uk** [qbalsdon/pico_rgb_keypad_hid#3]
How are you mounting the Pico Display? From what I have seen it goes on the rear of the Pico? Initially I thought it was mounted on top.

**Comment by qbalsdon** [comment]
Yeah you're right, normally it is, I just made a sort of jig and re-wired some of the plugs. It's a bit laggy but I suspect I'm on the wrong pins or not making use of PIOASM. But that is what the wiring diagram is trying to depict on the README

![Screenshot 2021-03-25 at 11 17 58](https://user-images.githubusercontent.com/1086536/112464781-d3ce8700-8d5b-11eb-9228-e3a24a2d0c33.png)

**Comment by kjbaker-uk** [comment]
Thank you.
