### ISSUE TITLE
No module named 'board'

### ISSUE THREAD

**Issue by mcbaer** [qbalsdon/pico_rgb_keypad_hid#4]
```
%Run code.py
Traceback (most recent call last):
  File "H:\code.py", line 2, in <module>
    import board
ModuleNotFoundError: No module named 'board'
```

I keep getting this error when I try to run the code.

![image](https://user-images.githubusercontent.com/14003870/115081720-6204db80-9eca-11eb-9985-2dc0dcb995cd.png)

**Comment by wildestpixel** [comment]
Ensure that you have flashed Circuitpython to the board firstly and follow all instructions. There can never be no module called board under cp as it is baked into the CP build. Suspect you are trying to run cp code on Micropython

**Comment by mB-PiBox** [comment]
> Circuitpython

Its a new pico, I've only ever put the file for CircuitPython on it.. and it rebooted, and shows as CIRUITPY in explorer which I added the lib files to
