### ISSUE TITLE
RuntimeError: No pull up found on SDA or SCL; check your wiring

### ISSUE THREAD

**Issue by ricuncu** [qbalsdon/pico_rgb_keypad_hid#7]
Hi, I'm trying to replicate your project, I bought a Pimoroni keypad and a pre-soldered pi pico, I tried the micropython examples from pimoroni and everything seems working (buttons and colors at least). When I try you code.py i always get the error

Traceback (most recent call last):
  File "<stdin>", line 50, in <module>
RuntimeError: No pull up found on SDA or SCL; check your wiring

I can't understand why, I also tried using all your files from scratch but I'm stuck with it.

Thanks
Riccardo

**Comment by qbalsdon** [comment]
Hey there! Just so you're aware this is a CircuitPython project... It differs from MicroPython in subtle ways: https://core-electronics.com.au/tutorials/circuitpython-vs-micropython-differences.html

The main reason I went that route was I couldn't get MicroPython to behave like a Human Interface Device (HID), like a keyboard / mouse. 

To install CircuitPython you'll need to follow these instructions: https://circuitpython.org/board/raspberry_pi_pico/

**Comment by qbalsdon** [comment]
If you are using CircuitPython I'll try spin it up sometime this week and get back to you.

**Comment by ricuncu** [comment]
Thank you! Yes I used micropython only to check if it was working, but then moved to CircuitPithon with the 6.3 stable (and also the 6.2 beta that you provided),

Thank you for your answer and feedback!
/R

**Comment by ricuncu** [comment]
Hi @qbalsdon, did you have time to check the issue I'm facing? 

Thank you!

**Comment by cverbiest** [comment]
check this post https://forums.pimoroni.com/t/pico-rgb-keypad-i2c-pullup-error/16142/17 could be issue with the board

**Comment by ricuncu** [comment]
Hmmm interesting, I have a brand new board here with me so maybe if I can find the time to solder it I can try with the new one.

Thanks!
