### ISSUE TITLE
Keys not responding to press events

### ISSUE THREAD

**Issue by Filemandev** [qbalsdon/pico_rgb_keypad_hid#8]
Hi,

I did everything the way you told me but i still don't get response from the keys.

When i push a key on the keypad there is nothing happening. 

Can you please help me.

**Comment by qbalsdon** [comment]
Does the standard build work? I did have to return one board to Pimoroni because certain keys didn't work

**Comment by Filemandev** [comment]
No the board works with the example code from pimoroni. But even the teams keyqonfig doesn't work.

**Comment by qbalsdon** [comment]
I hope you figure this out, unfortunately I can no longer maintain this repository
