### ISSUE TITLE
not really an issue but its an issue with me 

### ISSUE THREAD

**Issue by Roundhead22** [qbalsdon/pico_rgb_keypad_hid#9]
ok this isnt a problem with the code i am completely new to pico and micro python so i have no clue how to set the hid keyboard up

**Comment by qbalsdon** [comment]
Haha well I think problem number one is that in MICRO python you cannot have the Pico be an HID. You need to install CIRCUIT python.

Adafruit has a guide on this: https://learn.adafruit.com/circuitpython-essentials/circuitpython-hid-keyboard-and-mouse

**Comment by qbalsdon** [comment]
What I would recommend is make the board automatically type "Hello" when it is plugged in so you know that it's working without any of the other hardware.

**Comment by Roundhead22** [comment]
i have the modified firmware installed allthough i dont know how to add the
python code and the keybinds

**Comment by Roundhead22** [comment]
the guide i read on the readme said i needed to put these files in circuitpython/lib 
![image](https://user-images.githubusercontent.com/92760172/162814679-9dcf835b-7199-46a8-a112-e5e84d676620.png)

**Comment by Roundhead22** [comment]
im also getting this error
![image](https://user-images.githubusercontent.com/92760172/162944128-8506a75f-6af7-4e0b-8a1f-e90f1490afcc.png)
 where do i find the lib

**Comment by qbalsdon** [comment]
Did you copy the `lib` and `keyconfig` folders onto the pico as well?
